// <auto-generated />
using McCordMission4Take2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace McCordMission4Take2.Migrations
{
    [DbContext(typeof(MovieData))]
    [Migration("20220126232307_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("McCordMission4Take2.Models.MovieAdd", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationID");

                    b.ToTable("MovieAdds");

                    b.HasData(
                        new
                        {
                            ApplicationID = 1,
                            Category = "Comedy",
                            Director = "Rawson Thurber",
                            Edited = true,
                            Lent_To = "Connor Meadows",
                            Note = "This movie has been watched many a times in Newport Hills",
                            Rating = "PG-13",
                            Title = "Dodgeball"
                        },
                        new
                        {
                            ApplicationID = 2,
                            Category = "Romantic-Comedy",
                            Director = "Jon M. Chu",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Crazy Rich Asians"
                        },
                        new
                        {
                            ApplicationID = 3,
                            Category = "Animation",
                            Director = "Jon M. Chu",
                            Edited = false,
                            Rating = "PG",
                            Title = "Mulan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
