// <auto-generated />
using McCordMission4Take2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace McCordMission4Take2.Migrations
{
    [DbContext(typeof(MovieData))]
    partial class MovieDataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("McCordMission4Take2.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Romantic-Comedy"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Animation"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Drama"
                        });
                });

            modelBuilder.Entity("McCordMission4Take2.Models.MovieAdd", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("MovieAdds");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 1,
                            Director = "Rawson Thurber",
                            Edited = true,
                            Lent_To = "Connor Meadows",
                            Note = "This movie has been watched many a times in Newport Hills",
                            Rating = "PG-13",
                            Title = "Dodgeball"
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 2,
                            Director = "Jon M. Chu",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Crazy Rich Asians"
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 4,
                            Director = "Jon M. Chu",
                            Edited = false,
                            Rating = "PG",
                            Title = "Mulan"
                        });
                });

            modelBuilder.Entity("McCordMission4Take2.Models.MovieAdd", b =>
                {
                    b.HasOne("McCordMission4Take2.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
